#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: #@ data.values.ceph_csi_cephfs.namespace
stringData:
  # User ID should have required access to the 'pool' specified in the storage class
  # For statically provisioned volumes
  userID: #@ data.values.ceph_csi_cephfs.user_id
  userKey: #@ data.values.ceph_csi_cephfs.user_key 

  # For dynamically provisioned volumes
  adminID: #@ data.values.ceph_csi_cephfs.user_id
  adminKey: #@ data.values.ceph_csi_cephfs.user_key 
